#ifndef LANGFILES_SETTINGS_HPP__
#define LANGFILES_SETTINGS_HPP__

#define VERSION "1.00b"

#define LINE_BUFFER_SIZE 1024
#define MAX_STRING_SPACE 256
#define MID_STRING_SPACE 128
#define MIN_STRING_SPACE 24

#define LOG_MESSAGE_SIZE 256
#define ERROR_MESSAGE_SIZE 256

#define MAX_VARIABLE_SPACE 64
#define MAX_FUNCTION_SPACE 64

#define MAX_SCOPE_LEVEL 8

#define DEFAULT_MEM 1024

#define USING_DEBUG

#endif